version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: transfermarkt_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zfjvdspifj1341
      POSTGRES_DB: transfermarkt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: